from uuid import uuid4
songs = [{
        "name": "Under the City Stars",
        "cover": "https://chillhop.com/wp-content/uploads/2020/09/0255e8b8c74c90d4a27c594b3452b2daafae608d-1024x1024.jpg",
        "artist": "Aso, Middle School, Aviino",
        "audio": "https://mp3.chillhop.com/serve.php/?mp3=10074",
        "_id": "1",
        "active": False,
        "isLiked": False,
    },
    {
        "name": "Tokyo Drift",
        "cover": "/images/tokyo.jpg",
        "artist": "Teriyaki Boyz",
        "audio": "/images/tokyo.mp3",
        "_id": "2",
        "active": False,
        "isLiked": False,
    },
    {
        "name": "Bad Decisions",
        "cover": "/images/badDecisions.jpg",
        "artist": "benny blanco",
        "audio": "/images/badDecisions.mp3",
        "_id": "3",
        "active": False,
        "isLiked": False,
    },
    {
        "name": "RICKY",
        "cover": "/images/RICKY.jpg",
        "artist": "DENZELCURRYPH",
        "audio": "/images/RICKY.mp3",
        "_id": "4",
        "active": False,
        "isLiked": False,
    },
    {
        "name": "Get Back",
        "cover": "/images/GetBack.jpg",
        "artist": "Pop Smoke",
        "audio": "/images/GetBack.mp3",
        "_id": "5",
        "active": False,
        "isLiked": False,
    },
    {
        "name": "Best Friend",
        "cover": "/images/BestFriend.jpg",
        "artist": "50 Cent",
        "audio": "/images/BestFriend.mp3",
        "_id": "6",
        "active": False,
        "isLiked": False,
    },
]
